
 /*   CREACIÓN DE TABLAS DIMENSIONALES */
CREATE TABLE DIM_STATE TABLESPACE BIDATA AS
SELECT DISTINCT CUSTOMER_STATE STATE_NM, CUSTOMER_CITY CITY_NM FROM TBL_OLIST_CUSTOMERS
ORDER BY 1;

CREATE TABLE DIM_CUSTOMER TABLESPACE BIDATA AS
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_UNIQUE_ID, CUSTOMER_STATE STATE_NM FROM TBL_OLIST_CUSTOMERS;

CREATE TABLE DIM_PRODUCTO TABLESPACE BIDATA AS
SELECT DISTINCT PRODUCT_ID, PRICE, FREIGHT_VALUE FROM TBL_OLIST_ORDER_ITEMS;

INSERT INTO DIM_STATE
SELECT DISTINCT CUSTOMER_STATE STATE_NM, CUSTOMER_CITY CITY_NM FROM TBL_OLIST_CUSTOMERS
ORDER BY 1;

CREATE TABLE DIM_STATUS TABLESPACE BIDATA AS
SELECT
CASE WHEN ORDER_STATUS = 'created' THEN 1 
     WHEN ORDER_STATUS = 'processing' THEN 2
     WHEN ORDER_STATUS = 'approved' THEN 3
     WHEN ORDER_STATUS = 'invoiced' THEN 4
     WHEN ORDER_STATUS = 'unavailable' THEN 5
     WHEN ORDER_STATUS = 'shipped' THEN 6
     WHEN ORDER_STATUS = 'delivered' THEN 7 
     WHEN ORDER_STATUS = 'canceled' THEN 8
     END STATUS_ID,
     A.*
FROM
(
SELECT DISTINCT ORDER_STATUS FROM TBL_OLIST_ORDERS
) A
ORDER BY 1;

    /*CREACIÓN DE TABLAS INTERMEDIAS*/

CREATE TABLE TBL_ORDERS_STATUS  AS
SELECT DISTINCT A.*, CASE WHEN ORDER_STATUS = 'created' THEN 1 
     WHEN ORDER_STATUS = 'processing' THEN 2
     WHEN ORDER_STATUS = 'approved' THEN 3
     WHEN ORDER_STATUS = 'invoiced' THEN 4
     WHEN ORDER_STATUS = 'unavailable' THEN 5
     WHEN ORDER_STATUS = 'shipped' THEN 6
     WHEN ORDER_STATUS = 'delivered' THEN 7 
     WHEN ORDER_STATUS = 'canceled' THEN 8
     END STATUS_ID
     FROM TBL_OLIST_ORDERS A
     WHERE TRUNC(A.ORDER_PURCHASE_TIMESTAMP) = '12/5/2017';
     

CREATE TABLE TBL_DTL_ORDERS_STATUS AS
SELECT A.*, B.ORDER_ITEM_ID, B.PRODUCT_ID, B.SHIPPING_LIMIT_DATE
FROM TBL_ORDERS_STATUS A
LEFT JOIN TBL_OLIST_ORDER_ITEMS B ON A.ORDER_ID = B.ORDER_ID;


--- TABLA FINAL, HECHOS ----

CREATE TABLE TBL_ORDERS_FCT AS
SELECT DISTINCT A.ORDER_ID, TRUNC(A.ORDER_PURCHASE_TIMESTAMP)ORDER_PURCHASE_FCT, A.CUSTOMER_ID, B.CUSTOMER_UNIQUE_ID, D.STATUS_ID, A.ORDER_STATUS,
A.ORDER_ITEM_ID, B.STATE_NM, C.CITY_NM, A.ORDER_PURCHASE_TIMESTAMP, A.ORDER_APPROVED_AT, A.SHIPPING_LIMIT_DATE, A.ORDER_DELIVERED_CARRIER_DATE, 
A.ORDER_DELIVERED_CUSTOMER_DATE, A.ORDER_ESTIMATED_DELIVERY_DATE, E.PRICE, E.FREIGHT_VALUE,
SUM((E.PRICE*A.ORDER_ITEM_ID)+(E.FREIGHT_VALUE*A.ORDER_ITEM_ID)) TOTAL_ORDER
FROM TBL_DTL_ORDERS_STATUS A
LEFT JOIN DIM_CUSTOMER B ON A.CUSTOMER_ID = B.CUSTOMER_ID 
LEFT JOIN DIM_STATE C ON B.STATE_NM = C.STATE_NM	
LEFT JOIN DIM_STATUS D ON A.STATUS_ID = D.STATUS_ID
LEFT JOIN DIM_PRODUCTO E ON A.PRODUCT_ID = E.PRODUCT_ID
WHERE TRUNC(A.ORDER_PURCHASE_TIMESTAMP) = '12/5/2017' 
GROUP BY A.ORDER_ID, TRUNC(A.ORDER_PURCHASE_TIMESTAMP), A.CUSTOMER_ID, B.CUSTOMER_UNIQUE_ID, D.STATUS_ID, A.ORDER_STATUS,
A.ORDER_ITEM_ID, B.STATE_NM, C.CITY_NM, A.ORDER_PURCHASE_TIMESTAMP, A.ORDER_APPROVED_AT, A.SHIPPING_LIMIT_DATE, A.ORDER_DELIVERED_CARRIER_DATE, 
A.ORDER_DELIVERED_CUSTOMER_DATE, A.ORDER_ESTIMATED_DELIVERY_DATE, E.PRICE, E.FREIGHT_VALUE;


--- TABLA RESUMEN ---
CREATE TABLE TBL_SMMRY_ORDERS_FCT AS
SELECT SUM(CASE WHEN ORDER_ID IS NOT NULL THEN 1 ELSE 0 END) ORDERS, ORDER_PURCHASE_FCT,SUM(CASE WHEN CUSTOMER_ID IS NOT NULL THEN 1 ELSE 0 END)CUSTOMERS,
STATUS_ID, ORDER_STATUS, ORDER_ITEM_ID, STATE_NM, CITY_NM, TRUNC(ORDER_PURCHASE_TIMESTAMP)ORDER_PURCHASE_TIMESTAMP, 
TRUNC(ORDER_APPROVED_AT)ORDER_APPROVED_AT, TRUNC(SHIPPING_LIMIT_DATE)SHIPPING_LIMIT_DATE, 
TRUNC(ORDER_DELIVERED_CARRIER_DATE)ORDER_DELIVERED_CARRIER_DATE, TRUNC(ORDER_DELIVERED_CUSTOMER_DATE)ORDER_DELIVERED_CUSTOMER_DATE,
TRUNC(ORDER_ESTIMATED_DELIVERY_DATE)ORDER_ESTIMATED_DELIVERY_DATE, SUM(TOTAL_ORDER)TOTAL_ORDER
FROM TBL_ORDERS_FCT
WHERE ORDER_PURCHASE_FCT = '26/11/2017'
GROUP BY ORDER_PURCHASE_FCT, STATUS_ID, ORDER_STATUS, ORDER_ITEM_ID, STATE_NM, CITY_NM,TRUNC(ORDER_PURCHASE_TIMESTAMP), 
TRUNC(ORDER_APPROVED_AT), TRUNC(SHIPPING_LIMIT_DATE), TRUNC(ORDER_DELIVERED_CARRIER_DATE), TRUNC(ORDER_DELIVERED_CUSTOMER_DATE),
TRUNC(ORDER_ESTIMATED_DELIVERY_DATE) ;